
#' Simulated Annealing
#'
#' This is almost a precise re-write of the simulated annealing
#' function `stats::optim(method = "SANN")` as implemented in the file
#' `r-source/src/appl/optim.c`. In particular, temperature is updated
#' step by step with respect to the formula
#' $$ T^{(i)} = T_{\text{start}} / \log(((i-1) %/% tmax)*tmax + exp(1))$$
#' and new candidate points are generated using a Gaussian kernel
#' $$ p^{(i)}_j = p^{(i-1)} + \frac{T^{(i)}}{T_{\text{start}}} \cdot \varepsilon,$$
#'
#' where $\varepsilon\sim\mathcal N(0, 1)$.
#'
#' However, there are three main differences:
#' * This function is currently implemented completely in R, for easier debugging.
#' * This function returns a trace of all visited values as a `data.frame`.
#' * This function allows for bounded parameter spaces by using the methodology
#'   from chapter 6 of (Haario and Saksman 1991).
#'
#' The adaption for the case of bounded parameter spaces is as follows:
#' W.l.o.g. assume that boundaries are $[0,1]^n$. Let $p$ the current point
#' and $p^{\text{try}}$ the candidate generated by the Gauss kernel. Suppose
#' that $i$-th component is not in boundary, i.e. $p^{\text{try}}_i\notin [0, 1]$.
#' Then division by 2 with remainder gives us $p^{\text{try}}_i\mod 2\in [0, 2)$,
#' when identifying $\mathbb R/2\mathbb Z\cong [0, 2)$ as sets. Then either
#' $p^{\text{try}}_i\mod 2\in [0, 1]$ or $2 - p^{\text{try}}_i \mod 2\in [0, 1]$.
#' Then, use this updated component of the candidate.
#'
#' @param par numeric, start value for the algorithm
#' @param fn the function to be minimized
#' @param lower numeric, lower boundary of the parameter vector
#' @param upper numeric, upper boundary of the parameter vector
#' @param control a list of further control parameters for the algorithm
#'
#' @section Control parameters:
#'
#' The list `control` may contain the following objects:
#' * `maxit`: the maximal number of temperature steps, defaults to `10000`,
#' * `temp`: the initial temperature, defaults to `10``,`
#' * `tmax`: the maximal number of function evaluations at each
#'    temperature step, defaults to `10`.
#'
#' @return a list containing `par`, the parameter combination of the optimum,
#' `value`, the optimal function value, and `trace`, a `data.frame` of all visited
#' parameter values.
#'
#' @references Haario H, Saksman E. Simulated Annealing Process in General State Space. Advances in Applied Probability, Vol. 23, No. 4 (Dec., 1991), pp. 866-893, [https://doi.org/10.2307/1427681].
#' @export
#'
#' @examples
#' fun <- function(x) {1 - dnorm(x, mean = 0, sd = 20)*10}
#' res <- simann(par = -10, fn = fun,
#'               control = list(maxit = 10000,
#'                              temp = 2000))
#' plot(res$trace$it, res$trace$fn)
#' plot(res$trace$it, res$trace$par1)
#' # With boundaries and named parameters
#' resbd <- simann(par = c(x = -1), fn = fun,
#'                 lower = -2, upper = 2,
#'                 control = list(maxit = 10000,
#'                                temp = 2000))
#' plot(resbd$trace$it, resbd$trace$fn)
#' plot(resbd$trace$it, resbd$trace$x)
simann <- function(par, fn,
                   lower = NULL, upper = NULL,
                   control){
  maxit <- 10000
  temp <- 10
  tmax <- 10
  bounded <- !is.null(lower) | !is.null(upper)
  if(bounded){
    if(length(lower) != length(par) | length(upper) != length(par)){
      stop("Lower and upper bound must have the same length as the
           start vector!")
    }
    if(!all(lower < upper)){
      stop("Lower bound must be below upper bound!")
    }
  }
  if(!is.null(control$maxit)){
    maxit <- control$maxit
  }
  if(!is.null(control$tmax)){
    tmax <- control$tmax
  }
  if(!is.null(control$temp)){
    temp <- control$temp
  }
  p <- par
  y <- fn(par)
  popt <- par
  yopt <- y
  trace <- data.frame((1:maxit), rep(par, maxit), rep(y, maxit), rep(NA_real_, maxit))
  par_names <- names(par)
  fn_name <- names(y)
  if(is.null(par_names)){
    par_names <- paste0("par", (1:length(par)))
  }
  if(is.null(fn_name)){
    fn_name <- "fn"
  }
  names(trace) <- c("it", par_names, fn_name, "temp")

  for(i in (1:maxit)){
    tnow <- temp / log(((i-1) %/% tmax)*tmax + exp(1))
    scale <- tnow/temp
    ptry <- genptry(p, scale)
    if(bounded){
      for(j in (1:length(par))){

        # If coordinate j below lower boundary and there is no upper boundary,
        # then reflect along lower boundary.
        if(ptry[j] < lower[j] & upper[j] == Inf){
          ptry[j] <- 2*lower[j] - ptry[j]
        }
        # If coordinate j above upper boundary and there is no lower boundary,
        # then reflect along upper boundary.
        else if(ptry[j] > upper[j] & lower[j] == -Inf){
          ptry[j] <- 2*upper[j] - ptry[j]
        }
        # If there are finite upper and lower boundaries, alternately reflect
        # along upper and lower boundaries until we are in the interval.
        else if(ptry[j] > upper[j] | ptry[j] < lower[j]){
          phi_j <- phi(x = ptry[j], lower = lower[j], upper = upper[j]) %% 2
          if(1 >= phi_j){
            ptry[j] <- phiinv(x = phi_j, lower = lower[j], upper = upper[j])
          } else{
            ptry[j] <- phiinv(x = 2 - phi_j, lower = lower[j], upper = upper[j])
          }
        }
      }
    }
    ytry <- fn(ptry)
    dy <- ytry - y
    if(dy < 0){
      y <- ytry
      p <- ptry
    } else if(runif(1, 0, 1) < exp(-dy/(tnow))){
      y <- ytry
      p <- ptry
    }
    if(ytry < yopt){
      yopt <- ytry
      popt <- ptry
    }
    trace[i,] <- c(i, p, y, tnow)
  }
  return(list(par = popt,
              value = yopt,
              trace = trace))
}


#' Generate a candidate point in the neighborhood
#'
#' Using a Gaussian kernel of standard deviation *scale* around the current
#' point, this function generates a new point nearby.
#'
#' @param p a numeric vector
#' @param scale a real number, the radius of the Gaussian
#'
#' @return a numeric vector
#'
#' @examples
#' genptry(c(0, 0), 2)
genptry <- function(p, scale){
    return(p + scale * rnorm(n = length(p), mean = 0, sd = 1))
}
#' Transform an interval to the unit interval
#'
#' A monotonously increasing bijection on the real line that maps the interval
#' $[\text{l}, \text{u}]$ to the unit interval $[0, 1]$.
#'
#' @param x any real number
#' @param lower a real number, the lower bound of the interval
#' @param upper  a real number, the upper bound of the interval
#'
#' @return a real number
#'
#' @examples
#' phiinv(phi(7, 2, 3), 2, 3) == 7
phi <- function(x, lower, upper){
  return((x - lower)/(upper - lower))
}
#' Transform the unit interval to another interval
#'
#' A monotonously increasing bijection on the real line that maps the unit
#' interval $[0, 1]$ to the interval $[\text{lower}, \text{u}]$.
#'
#' @param x any real number
#' @param lower a real number, the lower bound of the interval
#' @param upper  a real number, the upper bound of the interval
#'
#' @return a real number
#'
#' @examples
#' phiinv(phi(7, 2, 3), 2, 3) == 7
phiinv <- function(x, lower, upper){
  return((upper - lower)*x + lower)
}
